	// let tour: number[] = twoopt.initialize();
	// console.log(`${tour}:${twoopt.isFinished()}`);
	// let tour2:number[] = twoopt.next(tour);
	// console.log(`${tour2}:${twoopt.isFinished()}`);
	// let tour3:number[] = twoopt.next(tour2);
	// console.log(`${tour3}:${twoopt.isFinished()}`);
	// let tour4: number[] =  twoopt.next(tour3);
	// console.log(`${tour4}:${twoopt.isFinished()}`);
	// let tour5:number[] = twoopt.next(tour4);
	// console.log(`${tour5}:${twoopt.isFinished()}`);
	// let tour6:number[] = twoopt.next(tour5);
	// console.log(`${tour6}:${twoopt.isFinished()}`);